baseurl = "https://renan-cunha.github.io/"
title = "Renan Cunha"
author = "You"
copyright = "Your Copyright"
canonifyurls = true
paginate = 5
customCSS = ["/home/renan/git/renancunha/static/style.css"]
googleAnalytics = ""
math = true
theme = "strange-case"

[params]
	colorScheme = "scheme-lightbrown"
	DateFormat = "2 Jan 2006"
	description = ""
	sidebarDescription = ""
	sidebarFreeText = "Computer Science student with interest in AI"
	piwikSiteID = ""
	piwikURL = ""

[[menu.main]]
    name = "Blog"
    url = "/posts"

[[menu.main]]
    name = "Categories"
    url = "/categories"

