baseurl = "https://renan-cunha.github.io/"
title = "Renan Cunha"
copyright = "Your Copyright"
canonifyurls = true
paginate = 5
customCSS = ["/home/renan/git/renancunha/static/style.css"]
googleAnalytics = "UA-159089871-1"
math = true
theme = "strange-case"

[params]
	colorScheme = "scheme-lightbrown"
	DateFormat = "2 Jan 2006"
    description = "AI, Data Science, and anything else."
	piwikSiteID = ""
	piwikURL = ""

[[menu.main]]
    name = "Blog"
    url = "/posts"

[[menu.main]]
    name = "Categories"
    url = "/categories"

